# Generated by Django 4.1.5 on 2023-01-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
